{
	"version": 1486232030,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/cruz-sheet0.png",
		"images/pseudo_floor-sheet0.png",
		"images/calice-sheet0.png",
		"images/calice-sheet1.png",
		"images/inceso-sheet0.png",
		"images/inceso-sheet1.png",
		"images/inceso-sheet2.png",
		"images/sprite3-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/potion-sheet0.png",
		"images/penta-sheet0.png",
		"images/bode-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"media/kick - 09.m4a",
		"media/kick - 09.ogg",
		"media/kick - 01.m4a",
		"media/kick - 01.ogg",
		"media/snare - 02.m4a",
		"media/snare - 02.ogg",
		"media/clap - 03.m4a",
		"media/clap - 03.ogg",
		"media/tom - 01.m4a",
		"media/tom - 01.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}